site_name: Open Research Network
site_url: https://openresearchnet.org

docs_dir: pages
site_dir: build

theme:
  name: null
  custom_dir: 'theme/'
  features:
    - content.code.copy
  palette:
    primary: indigo

extra_css:
  - css/style.css
  - css/index.css

extra_javascript:
  - js/bundle.js
  - js/search.js
  - js/index.json

nav:
  - Home: 'index.md'
  - Affiliations:
    - __index__: affiliations/index.md
    - Organizations: affiliations/organizations/index.md
    - Members: affiliations/members/index.md
    - Partnership: affiliations/partnership/index.md
    - Working Groups: affiliations/working-groups/index.md
  - Publications:
    - __index__: publications/index.md
  - About:
    - __index__: about/index.md
    - Team: about/team/index.md
    - Formula: about/formula/index.md
    - Funding: about/funding/index.md
  - Donate: 'donate/index.md'

markdown_extensions:
  - toc:
      permalink: " #"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - blogging:
      template: theme/blog-list.html
      dirs:
        - blog
      features:
        tags: {}

  - rss:
      abstract_chars_count: 160  # -1 for full content
      abstract_delimiter: <!-- more -->
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
        default_timezone: Europe/Paris
        default_time: "09:30"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
